app/controllers/ReportsController.php
<?php

/**
 * Home controller
 * @author John<johnerick8@gmail.com>
 */
class ReportsController extends Controller {

    public function init() {
        parent::init();
    }

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index','training','costs'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        //$this->redirect(array('inv/default/index'));
		$this->activeTab = MeModuleConstants::TAB_DHIS_REPORTS;
        $this->pageTitle = Lang::t('Reports');
		$model=new ReportForm();
		if(isset($_POST['ReportForm'])){
			$model->attributes=$_POST['ReportForm'];
			$condition='1=1';
			if($model->date_from!=null && $model->date_to!=null){
				$condition.=" AND `hire_date` between '".$model->date_from."' and '".$model->date_to."'";
			}elseif($model->date_from!=null && $model->date_to==null){
				$condition.=" AND `hire_date` >='".$model->date_from."'";
			}elseif($model->date_from==null && $model->date_to!=null){
				$condition.=" AND `hire_date` <='".$model->date_to."'";
			}
			if($model->dob_from!=null && $model->dob_to!=null){
				$condition.=" AND `birthdate` between '".$model->dob_from."' and '".$model->dob_to."'";
			}elseif($model->dob_from!=null && $model->dob_to==null){
				$condition.=" AND `birthdate` >='".$model->dob_from."'";
			}elseif($model->dob_from==null && $model->dob_to!=null){
				$condition.=" AND `birthdate` <='".$model->dob_to."'";
			}
			if($model->gender!=null){
				$condition.=" AND `gender`='".$model->gender."'";
			}
		$models=Employeeslist::model()->searchModel(array(),1000000, 'id', $condition);
		$posted=1;
		
		}
		if(isset($posted)&&$posted==1)
			$this->render('index', array('model'=>$model,'models'=>$models,'posted'=>$posted));

		else
        $this->render('index', array('model'=>$model));
    }

	 /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionTraining() {
        //$this->redirect(array('inv/default/index'));
		$this->activeTab = MeModuleConstants::TAB_DHIS_2_REPORTS;
        $this->pageTitle = Lang::t('Reports');
		$model=new ReportForm();
		if(isset($_POST['ReportForm'])){
			$model->attributes=$_POST['ReportForm'];
			$condition='1=1';
			if($model->date_from!=null && $model->date_to!=null){
				$condition.=" AND `start_date` between '".$model->date_from."' and '".$model->date_to."' AND  `end_date` between '".$model->date_from."' and '".$model->date_to."'";
			}elseif($model->date_from!=null && $model->date_to==null){
				$condition.=" AND `start_date` >='".$model->date_from."' AND `end_date` >='".$model->date_from."'";
			}elseif($model->date_from==null && $model->date_to!=null){
				$condition.=" AND `start_date` <='".$model->date_to."' AND `end_date` >='".$model->date_from."'";
			}
			if($model->country_id !=null){
				$condition .=" AND `country_of_inst` = '".$model->country_id."'";
			}if($model->skill_id !=null){
				$condition .=" AND `skill_id` = '".$model->skill_id."'";
			}
			
			
		$models = Empskills::model()->searchModel(array(), 10000000000, 'id',$condition);
		$posted=1;
		
		}
		if(isset($posted)&&$posted==1)
			$this->render('training', array('model'=>$model,'models'=>$models,'posted'=>$posted));

		else
        $this->render('training', array('model'=>$model));
    }
	
	public function actionCosts(){
		$this->activeTab = MeModuleConstants::TAB_BUDGETS_PERIODS;
        $this->pageTitle = Lang::t('Training Costs Reports');
		$this->render('costs');
	}

}

app/views/reports/_form.php
<?php
if (!isset($label_size)):
    $label_size = 2;
endif;
if (!isset($input_size)):
    $input_size = 8;
endif;
$label_class = "col-md-{$label_size} control-label";
$input_class = "col-md-{$input_size}";
$half_input_size = $input_size / 2;
$half_input_class = "col-md-{$half_input_size}";
?>
<?php
$form_id = 'employees-form';
$form = $this->beginWidget('CActiveForm', array(
    'id' => $form_id,
    'enableAjaxValidation' => false,
    'htmlOptions' => array('class' => 'form-horizontal'),
        ));
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo CHtml::encode($this->pageTitle) ?></h3>
    </div>

    <div class="panel-body">
        <?php echo CHtml::errorSummary($model, ""); ?>
        <div class="table-responsive">
         

<table class="table table-condensed"><tr style="background-color:inherit;background-image: none">
<th>Hire Date From</th>
<th>Hire Date to</th>
<th>DOB from</th>
<th>DOB to</th>
<th>Gender</th>
<th>Search</th>
</tr>
<tr><td>
                <?php echo CHtml::activeTextField($model, 'date_from', array('class' => 'form-control show-datepicker')); ?>
               
            </td><td>
                <?php echo CHtml::activeTextField($model, 'date_to', array('class' => 'form-control show-datepicker')); ?>
             
            </td> <td> <?php echo CHtml::activeTextField($model, 'dob_from', array('class' => 'form-control show-datepicker')); ?>
                
            </td><td>
                <?php echo CHtml::activeTextField($model, 'dob_to', array('class' => 'form-control show-datepicker')); ?>
              
            </td><td>
        <?php echo CHtml::activeDropDownList($model, 'gender', ReportForm::genderOptions(), array('class' => 'form-control', 'prompt' => 'Select Gender')); ?>&nbsp;&nbsp;
      </td><td>
        <button class="btn btn-sm btn-primary" type="submit">
            <i class="fa fa-ok"></i>
            <?php echo Lang::t('Create Report') ?>
        </button>
    </td>
	</tr>
	</table>
	</div>

    </div>

</div>
<?php $this->endWidget(); ?>

app/views/reports/_form_training.php
<?php
if (!isset($label_size)):
    $label_size = 2;
endif;
if (!isset($input_size)):
    $input_size = 8;
endif;
$label_class = "col-md-{$label_size} control-label";
$input_class = "col-md-{$input_size}";
$half_input_size = $input_size / 2;
$half_input_class = "col-md-{$half_input_size}";
?>
<?php
$form_id = 'employees-form';
$form = $this->beginWidget('CActiveForm', array(
    'id' => $form_id,
    'enableAjaxValidation' => false,
    'htmlOptions' => array('class' => 'form-horizontal'),
        ));
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo CHtml::encode($this->pageTitle) ?></h3>
    </div>

    <div class="panel-body">
        <?php echo CHtml::errorSummary($model, ""); ?>
        <div class="table-responsive">
         

<table class="table table-condensed"><tr style="background-color:inherit;background-image: none">
<th>Training Date From</th>
<th>Training Date to</th>
<th>Country of Training</th>
<th>skill</th>
<th>Search</th>
</tr>
<tr><td>
                <?php echo CHtml::activeTextField($model, 'date_from', array('class' => 'form-control show-datepicker')); ?>
               
            </td><td>
                <?php echo CHtml::activeTextField($model, 'date_to', array('class' => 'form-control show-datepicker')); ?>
             
            </td><td>
        <?php echo CHtml::activeDropDownList($model, 'skill_id', Skills::model()->getListData('id', 'skill'), array('class' => 'form-control')); ?>&nbsp;&nbsp;
      </td><td>
        <?php echo CHtml::activeDropDownList($model, 'skill_id', MeCountry::model()->getListData('id', 'name'), array('class' => 'form-control')); ?>&nbsp;&nbsp;
      </td><td>
        <button class="btn btn-sm btn-primary" type="submit">
            <i class="fa fa-ok"></i>
            <?php echo Lang::t('Create Report') ?>
        </button>
    </td>
	</tr>
	</table>
	</div>

    </div>

</div>
<?php $this->endWidget(); ?>

app/views/reports/_grid.php
<?php

$grid_id = 'employee-grid';
$this->widget('ext.MyGridView.ShowGrid', array(
    'title' => Common::pluralize($this->resourceLabel),
    'titleIcon' => '<i class="fa fa-truck"></i>',
    'showExportButton' => true,
    'showSearch' => false,
    'createButton' => array('visible' => $this->showLink($this->resource, Acl::ACTION_CREATE), 'modal' => false),
    'toolbarButtons' => array(),
    'showRefreshButton' => true,
    'grid' => array(
        'id' => $grid_id,
        'model' => $model,
        'rowCssClassExpression' => '', //'!$data->inuse?"bg-danger":""',
        'columns' => array(
            'id',
            array(
                'header' => Lang::t('Name'),
                'name' => 'Name',
                'value' => '$data->empname',
            ),
            'email',
            'mobile',
            array(
                'name' => 'birthdate',
                'value' => 'Common::formatDate($data->birthdate,"d-m-Y")',
            ),
			array(
                'name' => 'hire_date',
                'value' => 'Common::formatDate($data->hire_date,"d-m-Y")',
            ),
            'gender',
         
        ),
    )
));
?>

app/views/reports/_grid_training.php
<?php
$grid_id = 'empskills-grid';
$search_form_id = $grid_id . '-active-search-form';
?>
<br/>
<?php
$this->widget('application.components.widgets.GridView', array(
    'id' => $grid_id,
    'dataProvider' => $model->search(),
    'enablePagination' => $model->enablePagination,
    'enableSummary' => $model->enableSummary,
    'rowCssClassExpression' => '',
    'columns' => array(
		array('name'=>'Employee',
			   'value'=>'$data->getEmployee()'
	    ),
		array('name' => 'Country of Training',
            'value' => '$data->getCountry()'
			),
        array(
            'name' => 'skill_id',
            'value' => 'Skills::model()->get($data->skill_id,"skill")',
        ),
		
        'start_date',
        'end_date',
        array(
            'name' => 'proficiency_id',
            'value' => 'Proficiency::model()->get($data->proficiency_id,"prof_name")',
        ),
		'comp_not_used',
		'comp_used',
		'competencies',
		'certifying_body',
		'certification'
      
    ),
));
?>

app/views/reports/_tab.php
<ul class="nav nav-tabs order-tabs">
    <li class="<?php echo $this->activeTab === MeModuleConstants::TAB_DHIS_REPORTS ? 'active' : '' ?>"><a href="<?php echo $this->createUrl('reports/index') ?>"><span><i class="fa fa-circle text-success"></i> <?php echo Lang::t('Employee Report') ?></span></a></li>
    <li class=" <?php echo $this->activeTab === MeModuleConstants::TAB_DHIS_2_REPORTS ? 'active' : '' ?>"><a href="<?php echo $this->createUrl('reports/training') ?>"><span><i class="fa fa-circle text-success"></i> <?php echo Lang::t('Training Report') ?></span></a></li>
    <li class=" <?php echo $this->activeTab === MeModuleConstants::TAB_BUDGETS_PERIODS ? 'active' : '' ?>"><a href="<?php echo $this->createUrl('reports/costs') ?>"><span><i class="fa fa-circle text-success"></i> <?php echo Lang::t('Training Costs Report') ?></span></a></li>
    

    <li class="pull-right">
        <a href="<?php echo $this->createUrl('reports/index') ?>"><i class="fa fa-angle-double-left"></i> <?php echo Lang::t('Back to Reports') ?></a>
    </li>
</ul>

app/views/reports/_valuationgrid.php
<?php
$grid_id = 'rq_approval_list-grid';
$search_form_id = $grid_id . '-active-search-form';
?>
<div class="jarviswidget jarviswidget-color-darken" id="wid-id-<?php echo $grid_id ?>" data-widget-editbutton="false" data-widget-deletebutton="false">
    <header>
        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
        <h2><?php echo Lang::t('Valuation Pending My approval') ?> </h2>
    </header>
    <!-- widget div-->
    <div>
        <!-- widget content -->
        <div class="widget-body no-padding">
            <div class="dataTables_wrapper form-inline">

                <div class="dt-top-row">

                    <div class="dataTables_filter">


                    </div>
                </div>
                <?php
                $this->widget('application.components.widgets.GridView', array(
                    'id' => $grid_id,
                    'dataProvider' => $model->search(),
                    'enablePagination' => $model->enablePagination,
                    'enableSummary' => '',
                    'columns' => array(
                        'id',
                        array(
                            'name' => 'rfq_id',
                            'value' => 'Rfq::model()->get($data->rfq_id,"ref_no")'
                        ),
                        'valuation_ref',
                        array(
                            'class' => 'ButtonColumn',
                            'template' => '{download}{approve}',
                            'htmlOptions' => array('style' => 'width: 150px;'),
                            'buttons' => array(
                                'download' => array(
                                    'imageUrl' => false,
                                    'label' => '<i class="fa fa-download fa-2x yellow text-success"></i>',
                                    'url' => 'Yii::app()->controller->createUrl("/proc/rfqValuationdataHeader/download",array("id"=>$data->id))',
                                    'visible' => '$data->docExists()?true:false',
                                    'options' => array(
                                        'class' => '',
                                        'title' => Lang::t('Download'),
                                    ),
                                ),
                                'approve' => array(
                                    'imageUrl' => false,
                                    'label' => '<i class="fa fa-cogs fa-1x "></i> ' . Lang::t(Constants::LABEL_ACTION),
                                    'url' => 'Yii::app()->controller->createUrl("/proc/rfqValuationdataHeader/myactions",array("id"=>$data->id))',
                                    'visible' => '$this->grid->owner->showLink("' . ProcModuleConstants::RES_RFQ_VALUATION_DATA . '","' . Acl::ACTION_UPDATE . '")?true:false',
                                    'options' => array(
                                        'class' => ' show_modal_form',
                                        'title' => Lang::t(Constants::LABEL_ACTION),
                                    ),
                                ),
                            )
                        ),
                    ),
                ));
                ?>
            </div>
        </div>
    </div>
</div>

app/views/reports/costs.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
<?php $this->renderPartial('_tab'); ?>

    <div class="col-md-12">
	 <div class="well well-lights">
	
                <div class="row">
                        <?php //$this->renderPartial('_form_training', array('model' => $model)); ?>
						<a href="#"><img src="<?php echo Yii::app()->theme->baseUrl . '/img/under-construction.png' ?>" class="pull-left padding-10 " alt="" style="max-width: 400px;"></a>
                </div>
        <div class="row">
        <?php 
		if(isset($posted)&&$posted==1)
		//$this->renderPartial('_grid_training', array('model' => $models)); ?>
    </div>
    </div>
	</div>
</div>

app/views/reports/index.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
<?php $this->renderPartial('_tab'); ?>

    <div class="col-md-12">
	 <div class="well well-lights">
	
                <div class="row">
                        <?php $this->renderPartial('_form', array('model' => $model)); ?>
                </div>
        <div class="row">
        <?php 
		if(isset($posted)&&$posted==1)
		$this->renderPartial('_grid', array('model' => $models)); ?>
    </div>
    </div>
	</div>
</div>

app/views/reports/training.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
<?php $this->renderPartial('_tab'); ?>

    <div class="col-md-12">
	 <div class="well well-lights">
	
                <div class="row">
                        <?php $this->renderPartial('_form_training', array('model' => $model)); ?>
                </div>
        <div class="row">
        <?php 
		if(isset($posted)&&$posted==1)
		$this->renderPartial('_grid_training', array('model' => $models)); ?>
    </div>
    </div>
	</div>
</div>